version: '3.3'
services:
  REL:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '6006:3306'
    volumes:
      - my-db:/var/lib          /mysql
  adminer:
    image: dockette/adminer:full-php5
    ports:
      - '6060:8080'
volumes:
  my-db: