
server:
  port: 6666
spring:
  datasource:
    url: jdbc:mysql://localhost:6006/REL?createDatabaseIfNotExist=true
    username: root
    password: password
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: false
    open-in-view: true